"""init

Revision ID: 83f13c5cff25
Revises: 
Create Date: 2026-01-23 23:53:42.249071
"""

from alembic import op
import sqlalchemy as sa



revision = '83f13c5cff25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skazki',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription', sa.String(length=32), nullable=False),
    sa.Column('subscription_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('audio_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tts_minutes', sa.Float(), nullable=False),
    sa.Column('tales_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tales')
    op.drop_table('stats')
    op.drop_table('users')
    op.drop_table('skazki')
    # ### end Alembic commands ###
