"""add favorite flag

Revision ID: bd25287df05c
Revises: 83f13c5cff25
Create Date: 2026-01-24 12:45:53.654325
"""

from alembic import op
import sqlalchemy as sa



revision = 'bd25287df05c'
down_revision = '83f13c5cff25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tales', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tales', 'is_favorite')
    # ### end Alembic commands ###
